"""
Django settings for dcrm project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os # llamar para que funcione las rutas

try:
    from dotenv import load_dotenv
except ImportError:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv is not None:
    load_dotenv(BASE_DIR.parent / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-wrd@k5c63l-25ln)85jwma^uf$he_n077de(m!-(rhiu5#*d+q",
)

DEBUG = os.environ.get("DEBUG", "True").lower() == "true"

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]


# Application definition
# 4. Seguridad en la base de datos
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'website',# por defecto no se crea, hay que crearla con el comando "python manage.py startapp website"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dcrm.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dcrm.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Por defecto se usa sqlite3, pero se puede cambiar por otro motor de base de datos como MySQL, PostgreSQL, etc.
# 4. Seguridad en la base de datos
DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.environ.get('DB_NAME', 'clientes'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'website', 'templates', 'static'),
] # Agregar esta línea para indicar la carpeta donde se encuentran los archivos estáticos

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

# 4 capas de seguridad
# 1. Seguridad en la red
 # secure_ssl_redirect = True # Redirigir todas las solicitudes a HTTPS
session_cookie_secure = True # Asegurar que las cookies de sesión solo se envíen a través de HTTPS
csrf_cookie_secure = True # Asegurar que las cookies de CSRF solo se envíen a través de HTTPS
secure_hsts_seconds = 31536000 # Habilitar HTTP Strict Transport Security (HSTS) para proteger contra ataques de downgrade
secure_hsts_include_subdomains = True # Incluir subdominios en HSTS
cookies_secure = True # Asegurar que las cookies solo se envíen a través de HTTPS
secure_hsts_preload = True # Habilitar la inclusión en la lista de precarga de HSTS para mejorar la seguridad
session_cookie_secure = True # Asegurar que las cookies de sesión solo se envíen a través de HTTPS
## expiracion de sesiones
SESSION_COOKIE_AGE = 3000 # Establecer la duración de la sesión en segundos (en este caso, 3000 segundos o 50 minutos)

SESSION_EXPIRE_AT_BROWSER_CLOSE = True
#cierra sesion si no hay eventos dentro la pagina
SESSION_SAVE_EVERY_REQUEST = True


csrf_cookie_secure = True # Asegurar que las cookies de CSRF solo se envíen a través de HTTPS
# 2. Seguridad en la aplicación
secure_content_type_nosniff = True # Evitar que el navegador intente adivinar el tipo de contenido
secure_browser_xss_filter = True # Habilitar el filtro de XSS del navegador
'django.middleware.security.SecurityMiddleware', # Agregar esta línea en MIDDLEWARE para habilitar la seguridad en la aplicación

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True # Cambiar a False en producción para evitar mostrar información sensible en caso de errores
# 3. Seguridad en el servidor
# ALLOWED_HOSTS = ['localhost', 'tu_dominio.com'] # Cambiar por el dominio de tu sitio web para evitar ataques de host header

# 4. Seguridad en la base de datos
# Asegurar que la base de datos esté protegida con una contraseña segura y que solo se permita el acceso desde direcciones IP confiables. Además, es recomendable usar un motor de base de datos que ofrezca características de seguridad avanzadas, como cifrado de datos en reposo y en tránsito, autenticación fuerte, etc.

